sudo: required

arch:
  packages:
    - mingw-w64-gcc
    - mingw-w64-winpthreads
  script:
    - "./build_script.sh"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
